# Generated by Django 5.1.15 on 2026-08-28 17:11

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('email', models.EmailField(db_index=True, help_text='Required. Must be a valid, unique email address.', max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, help_text='User given name.', max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, help_text='User family name.', max_length=150, verbose_name='last name')),
                ('avatar_url', models.URLField(blank=True, help_text='Profile picture URL (e.g. from Google profile).', max_length=500, null=True, verbose_name='avatar URL')),
                ('auth_provider', models.CharField(choices=[('email', 'Email and Password'), ('google', 'Google OAuth')], default='email', help_text='The primary authentication method used by this account.', max_length=20, verbose_name='auth provider')),
                ('google_id', models.CharField(blank=True, db_index=True, help_text='Unique subject identifier provided by Google OAuth.', max_length=255, null=True, unique=True, verbose_name='Google User ID')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into the Django admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user account should be treated as active.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-created_at'],
            },
        ),
    ]
