# Generated by Django 5.1.15 on 2026-08-28 17:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('name', models.CharField(help_text='Display name of the workspace (e.g., HR & People, Engineering, Finance).', max_length=255, verbose_name='workspace name')),
                ('slug', models.SlugField(help_text='URL-friendly unique identifier for the workspace.', max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, help_text='Optional summary of the knowledge domain contained in this workspace.', verbose_name='description')),
                ('is_active', models.BooleanField(default=True, help_text='Controls whether this workspace is currently operational.', verbose_name='is active')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who originally created this workspace.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'workspace',
                'verbose_name_plural': 'workspaces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', help_text='Access level granted to the user within this workspace.', max_length=20, verbose_name='role')),
                ('user', models.ForeignKey(help_text='The member user.', on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='The workspace the user belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'workspace membership',
                'verbose_name_plural': 'workspace memberships',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'user'], name='workspaces__workspa_49c7e4_idx'), models.Index(fields=['user', 'role'], name='workspaces__user_id_ce56fb_idx')],
                'unique_together': {('workspace', 'user')},
            },
        ),
    ]
