# Generated by Django 5.1.15 on 2026-09-10 16:42

import apps.workspaces.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('email', models.EmailField(db_index=True, help_text='Email address of the invited colleague or teammate.', max_length=254, verbose_name='recipient email')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', help_text='The RBAC role granted upon accepting this invitation.', max_length=20, verbose_name='assigned role')),
                ('token', models.CharField(db_index=True, default=apps.workspaces.models.generate_invitation_token, help_text='Secure 64-character URL token for one-time verification.', max_length=64, unique=True, verbose_name='invitation token')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20, verbose_name='status')),
                ('expires_at', models.DateTimeField(default=apps.workspaces.models.default_invitation_expiry, help_text='Expiration timestamp (defaults to 7 days from creation).', verbose_name='expires at')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='accepted at')),
                ('accepted_by', models.ForeignKey(blank=True, help_text='User account that redeemed the invitation token.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_workspace_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(help_text='The workspace Admin who generated this invitation.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_workspace_invitations', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='The workspace the recipient is invited to join.', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'workspace invitation',
                'verbose_name_plural': 'workspace invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='workspaces__workspa_bea08e_idx'), models.Index(fields=['email', 'status'], name='workspaces__email_efe80b_idx'), models.Index(fields=['token', 'status'], name='workspaces__token_bd9df9_idx')],
            },
        ),
    ]
