# Generated by Django 5.1.15 on 2026-09-04 13:32

import apps.documents.services.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('title', models.CharField(db_index=True, help_text='Human-readable title of the document.', max_length=255, verbose_name='document title')),
                ('description', models.TextField(blank=True, help_text='Optional summary of the document contents or purpose.', verbose_name='description')),
                ('file_type', models.CharField(choices=[('PDF', 'Portable Document Format (.pdf)'), ('DOCX', 'Microsoft Word (.docx)'), ('TXT', 'Plain Text (.txt)'), ('MD', 'Markdown (.md)'), ('CSV', 'Comma-Separated Values (.csv)'), ('OTHER', 'Other / Unknown')], default='OTHER', help_text='Format of the primary uploaded document.', max_length=20, verbose_name='file type')),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('QUEUED', 'Queued for Processing'), ('PROCESSING', 'Extracting Content & Chunking'), ('EMBEDDING', 'Generating Vector Embeddings'), ('READY', 'Ready for RAG Search'), ('FAILED', 'Processing Failed'), ('ARCHIVED', 'Archived')], db_index=True, default='UPLOADED', help_text='Current processing and search-readiness status.', max_length=20, verbose_name='lifecycle status')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Controls whether this document is active or soft-deleted/archived.', verbose_name='is active')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who uploaded the initial version of this document.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='The workspace this document belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('version_number', models.PositiveIntegerField(default=1, help_text='Sequential version number (e.g. 1, 2, 3...).', verbose_name='version number')),
                ('file', models.FileField(help_text='The physical file stored in local storage or S3.', max_length=500, upload_to=apps.documents.services.storage.document_upload_path, verbose_name='document file')),
                ('original_filename', models.CharField(help_text='The original filename as uploaded by the user.', max_length=255, verbose_name='original filename')),
                ('file_size_bytes', models.BigIntegerField(default=0, help_text='Exact size of the uploaded file in bytes.', verbose_name='file size in bytes')),
                ('file_hash_sha256', models.CharField(db_index=True, help_text='Cryptographic SHA-256 checksum for content deduplication & integrity.', max_length=64, verbose_name='SHA-256 hash')),
                ('mime_type', models.CharField(blank=True, help_text='MIME type detected for this file (e.g. application/pdf).', max_length=100, verbose_name='MIME type')),
                ('processing_status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('QUEUED', 'Queued for Processing'), ('PROCESSING', 'Extracting Content & Chunking'), ('EMBEDDING', 'Generating Vector Embeddings'), ('READY', 'Ready for RAG Search'), ('FAILED', 'Processing Failed'), ('ARCHIVED', 'Archived')], db_index=True, default='UPLOADED', help_text='Status of the ingestion/chunking pipeline for this version.', max_length=20, verbose_name='processing status')),
                ('error_message', models.TextField(blank=True, help_text='Error traceback if processing failed.', verbose_name='error message')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this version is the active one used in RAG retrieval.', verbose_name='is active version')),
                ('change_summary', models.CharField(blank=True, help_text='Optional note describing what changed in this version.', max_length=255, verbose_name='change summary')),
                ('document', models.ForeignKey(help_text='The parent document this version belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded this specific version.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_document_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document version',
                'verbose_name_plural': 'document versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workspace', 'is_active', 'status'], name='documents_d_workspa_238307_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workspace', 'title'], name='documents_d_workspa_decbf7_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['document', 'version_number'], name='documents_d_documen_68fe34_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['file_hash_sha256'], name='documents_d_file_ha_8c3a57_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version_number')},
        ),
    ]
