# Generated by Django 5.1.15 on 2026-09-04 14:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('chunk_index', models.PositiveIntegerField(help_text='Zero-indexed sequential position of this chunk within the document version.', verbose_name='chunk index')),
                ('content', models.TextField(help_text='The extracted textual content of the chunk.', verbose_name='content')),
                ('page_number', models.PositiveIntegerField(blank=True, help_text='1-indexed page number if source is paginated (PDF), otherwise null.', null=True, verbose_name='page number')),
                ('section_header', models.CharField(blank=True, help_text='Nearest preceding heading or section title.', max_length=255, verbose_name='section header')),
                ('char_count', models.PositiveIntegerField(default=0, help_text='Number of characters in this chunk.', verbose_name='character count')),
                ('token_count_estimate', models.PositiveIntegerField(default=0, help_text='Approximated token count (~4 characters per token).', verbose_name='estimated token count')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional contextual metadata (e.g. source filename, language, custom tags).', verbose_name='metadata')),
                ('document', models.ForeignKey(help_text='The document this chunk belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
                ('version', models.ForeignKey(help_text='The specific document version this chunk was extracted from.', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.documentversion')),
                ('workspace', models.ForeignKey(help_text='Denormalized workspace reference for fast multi-tenant filtering.', on_delete=django.db.models.deletion.CASCADE, related_name='document_chunks', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'document chunk',
                'verbose_name_plural': 'document chunks',
                'ordering': ['chunk_index'],
                'indexes': [models.Index(fields=['workspace', 'document'], name='documents_d_workspa_714890_idx'), models.Index(fields=['version', 'chunk_index'], name='documents_d_version_5e01ee_idx')],
                'unique_together': {('version', 'chunk_index')},
            },
        ),
    ]
