# Generated by Django 5.1.15 on 2026-09-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_pgvector_embedding'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='embedding',
            new_name='documents_e_workspa_58af18_idx',
            old_name='documents_e_workspa_b1a329_idx',
        ),
        migrations.RenameIndex(
            model_name='embedding',
            new_name='documents_e_documen_25c2c0_idx',
            old_name='documents_e_documen_459a0f_idx',
        ),
        migrations.AlterField(
            model_name='embedding',
            name='model_name',
            field=models.CharField(default='text-embedding-3-small', help_text='Embedding model used (e.g. text-embedding-3-small, text-embedding-004, bge-small-en-v1.5).', max_length=100, verbose_name='model name'),
        ),
    ]
