# Generated by Django 5.1.15 on 2026-09-08 12:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0004_rename_documents_e_workspa_b1a329_idx_documents_e_workspa_58af18_idx_and_more'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('title', models.CharField(blank=True, default='New Conversation', help_text='Short descriptive title of the conversation thread.', max_length=255, verbose_name='title')),
                ('is_active', models.BooleanField(default=True, help_text='Soft deletion flag for conversations.', verbose_name='is active')),
                ('user', models.ForeignKey(help_text='The user who initiated this conversation.', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='The workspace this conversation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'conversation',
                'verbose_name_plural': 'conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], default='user', help_text='The message sender role.', max_length=20, verbose_name='role')),
                ('content', models.TextField(help_text='Raw textual content of the message.', verbose_name='content')),
                ('prompt_tokens', models.PositiveIntegerField(default=0, help_text='Estimated or actual tokens in prompt.', verbose_name='prompt tokens')),
                ('completion_tokens', models.PositiveIntegerField(default=0, help_text='Tokens generated in response.', verbose_name='completion tokens')),
                ('total_tokens', models.PositiveIntegerField(default=0, help_text='Total token consumption for this turn.', verbose_name='total tokens')),
                ('latency_ms', models.PositiveIntegerField(default=0, help_text='End-to-end generation latency in milliseconds.', verbose_name='latency in ms')),
                ('model_name', models.CharField(blank=True, help_text='The LLM model used (e.g. gemini-1.5-flash, gpt-4o-mini).', max_length=100, verbose_name='model name')),
                ('error_message', models.TextField(blank=True, help_text='Recorded error details if generation failed.', verbose_name='error message')),
                ('conversation', models.ForeignKey(help_text='The conversation this message belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('citation_index', models.PositiveIntegerField(help_text='1-based citation index corresponding to [1], [2] in text.', verbose_name='citation index')),
                ('similarity_score', models.FloatField(default=0.0, help_text='Vector search cosine similarity score (0.0 to 1.0).', verbose_name='similarity score')),
                ('document_title', models.CharField(help_text='Denormalized document title for fast frontend rendering.', max_length=255, verbose_name='document title')),
                ('original_filename', models.CharField(blank=True, help_text='Denormalized source filename.', max_length=255, verbose_name='original filename')),
                ('section_header', models.CharField(blank=True, help_text='Section header where this chunk was extracted.', max_length=255, verbose_name='section header')),
                ('page_number', models.IntegerField(blank=True, help_text='Page number for PDF documents.', null=True, verbose_name='page number')),
                ('snippet', models.TextField(blank=True, help_text='Brief preview snippet of the source chunk for citation popovers.', verbose_name='text snippet')),
                ('chunk', models.ForeignKey(blank=True, help_text='Reference to the specific document chunk cited.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cited_in_messages', to='documents.documentchunk')),
                ('message', models.ForeignKey(help_text='The assistant message this citation supports.', on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='chat.message')),
            ],
            options={
                'verbose_name': 'message source',
                'verbose_name_plural': 'message sources',
                'ordering': ['citation_index'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['workspace', 'user', '-updated_at'], name='chat_conver_workspa_a47eb9_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_messag_convers_3154fc_idx'),
        ),
        migrations.AddIndex(
            model_name='messagesource',
            index=models.Index(fields=['message', 'citation_index'], name='chat_messag_message_fdccb4_idx'),
        ),
    ]
